name: Deploy to SAS Viya

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: List files in workflows directory
      run: |
        ls -l /hello-world-sas-viya/.github/workflows/
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        node-version: '20'

    - name: Install dependencies
      run: |
        pip install saspy requests

    - name: Deploy to SAS Viya
      run: |
        python /hello-world-sas-viya/.github/workflows/deploy_to_sas.py
      env:
        VIYA_HOST: ${{ secrets.VIYA_HOST }}
        VIYA_USER: ${{ secrets.VIYA_USER }}
        VIYA_PASSWORD: ${{ secrets.VIYA_PASSWORD }}
